"""Initial schema migration

Revision ID: 051cb34a4792
Revises: 
Create Date: 2026-08-10 01:15:36.829233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051cb34a4792'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('machine_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('air_temperature', sa.Float(), nullable=False),
    sa.Column('process_temperature', sa.Float(), nullable=False),
    sa.Column('rotational_speed', sa.Integer(), nullable=False),
    sa.Column('torque', sa.Float(), nullable=False),
    sa.Column('tool_wear', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('machine_id')
    )
    op.create_table('parts_inventory',
    sa.Column('part_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('min_required', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('part_id'),
    sa.UniqueConstraint('part_name')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=True),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('predicted_failure', sa.String(length=255), nullable=False),
    sa.Column('time_to_failure', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('action_required', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.recommendation_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_orders')
    op.drop_table('recommendations')
    op.drop_table('predictions')
    op.drop_table('alerts')
    op.drop_table('parts_inventory')
    op.drop_table('machines')
    # ### end Alembic commands ###
